# Exemplo de arquivo de configuração para Azure App Service
# Este é apenas um exemplo e pode precisar ser ajustado
# com base nas suas configurações específicas e requisitos.

kind: app
apiVersion: v1alpha1

properties:
  # Nome da sua aplicação App Service (substitua pelo seu nome desejado)
  name: my-nextjs-app-service
  # Localização geográfica onde o App Service será implantado (substitua pela sua localização)
  location: West Europe
  # Plano do App Service (escolha o plano apropriado para suas necessidades)
  appServicePlan:
    name: my-app-service-plan
    resourceGroup: my-resource-group # Substitua pelo nome do seu grupo de recursos
    sku: B1 # Exemplo: B1 (Básico), S1 (Padrão), P1v2 (Premium v2), etc.
    capacity: 1 # Número de instâncias

  # Configurações da aplicação
  siteConfig:
    # Runtime stack (especifique a versão do Node.js)
    linuxFxVersion: 'NODE|18-lts' # Exemplo para Node.js 18 LTS
    # Comando de inicialização da aplicação (substitua se necessário)
    # Para Next.js, 'npm start' geralmente inicia o servidor.
    startupCommand: 'npm start'
    # Defina a porta que a aplicação escuta (geralmente 8080 no Azure App Service)
    # Certifique-se de que sua aplicação Next.js esteja configurada para escutar nesta porta
    appSettings:
      - name: PORT
        value: 8080
      # Outras variáveis de ambiente que sua aplicação pode precisar
      # - name: API_URL
      #   value: https://my-backend-api.azurewebsites.net
      # - name: DATABASE_CONNECTION_STRING
      #   value: ...

  # Outras propriedades, se necessário
  # resourceGroup: my-resource-group # Pode ser definido aqui ou no plano

# Autenticação e Autorização (exemplo básico - use configurações mais seguras em produção)
# authSettingsV2:
#   enabled: true
#   unauthenticatedClientAction: AllowAnonymous # Ou RedirectToLoginPage
#   # Configurações para provedores de identidade (Azure AD, Google, etc.)

# Networking (exemplo básico)
# virtualNetworkSubnetResourceId: /subscriptions/.../resourceGroups/.../providers/Microsoft.Network/virtualNetworks/.../subnets/...